### ISSUE TITLE
are we going to have svg version too in the future

### ISSUE THREAD

**Issue by swapnilsarwe** [voidlabs/versafix-social-icons#10]
Hey Team,

Just curious, are we planning to have svg formats for the icons in the future?
If yes - let me know if I could help.

**Comment by bago** [comment]
Well, SVG in email is useless today:
https://www.caniemail.com/features/image-svg/

Once Google and Microsoft will start accepting SVG in their email clients and their old versions not supporting SVG won't be used anymore we'll take care of it! (spoiler: it won't happen soon)

**Comment by swapnilsarwe** [comment]
Got it @bago . 
Keep up the good work.
