### ISSUE TITLE
Can we update twitter to X?

### ISSUE THREAD

**Issue by themak1985** [voidlabs/versafix-social-icons#12]
Twitter is now X - can we upgrade this icon pack to reflect the new change?

Sharing links if helpful:
https://fontawesome.com/icons/x-twitter?f=brands&s=solid
https://about.twitter.com/en/who-we-are/brand-toolkit

**Comment by CsarRamos** [comment]
Interested too, hello @bago is planned for a new version or do you need me to prepare a pull-request? 

Thanks!

**Comment by bago** [comment]
I pushed it, but I have to think better about it before releasing as I'm not sure replacing the old icon reusing its name is the best choice over creating a new name for the X icon and leave "tw" to the old twitter icon (there are conflicting implication at the template level and about static assets caching).

**Comment by CsarRamos** [comment]
Hi @bago, thank you very much for including it in the template, I just wanted to ask if there is an estimated date for a new release  of mosaico with template.
